coverage:
  precision: 2
  round: down
  status:
    project:
      form-builder:
        target: 90%
        flags:
          - form-builder
      form-redux:
        target: 90%
        flags:
          - form-redux
      form-context:
        target: 90%
        flags:
          - form-context
      form-validation-rule-list:
        target: 90%
        flags:
          - form-validation-rule-list
    patch:
      default:
        enabled: no
        if_not_found: success
    changes:
      default:
        enabled: no
        if_not_found: success
flags:
  form-builder:
    paths:
      - libs/form-builder/src
  form-redux:
    paths:
      - libs/form-redux/src
  form-context:
    paths:
      - libs/form-context/src
  form-validation-rule-list:
    paths:
      - libs/form-validation-rule-list/src

ignore:
  - "apps/demo/**/*"
  - "apps/docsite/**/*"
  - "libs/form-editor/**/*"
  - "libs/examples/**/*"
