name: deploy-docusaurus

on:
  # push:
  #   branches: [master]
  # pull_request:
  #   branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 6
      # Node is required for npm
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "14"
      # Install and build Docusaurus website
      - name: Build Docusaurus website
        run: |
          pnpm install --no-progress --frozen-lockfile
          pnpm lint docsite
          pnpm build docsite
          pnpm e2e docsite-e2e
      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: dist/apps/docsite
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
