name: 🏷 Automatic Labelling

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened, reopened]

jobs:
  issues:
    name: Label Issue
    if: ${{ Boolean(github.event.issue) == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check if author is an organization member
        id: is_organization_member
        uses: jamessingleton/is-organization-member@v1
        with:
          organization: BedrockStreaming
          username: ${{ github.event.issue.user.login }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: initial labeling
        uses: andymckay/labeler@master
        if: |
          steps.is_organization_member.outputs.result == true
        with:
          add-labels: "Bedrock"

  pr:
    name: Label Issue
    if: ${{ Boolean(github.event.pull_request) == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check if author is an organization member
        id: is_organization_member
        uses: jamessingleton/is-organization-member@v1
        with:
          organization: BedrockStreaming
          username: ${{ github.event.pull_request.user.login }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: initial labeling
        uses: andymckay/labeler@master
        if: |
          steps.is_organization_member.outputs.result == true
        with:
          add-labels: "Bedrock"

