name: CI
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' }}
    steps:
      - uses: actions/checkout@v2
        name: Checkout [master]
        with:
          fetch-depth: 0
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
        with:
          main-branch-name: 'master'
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 6
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: npx nx affected --target=lint --parallel --max-parallel=3
      - run: npx nx affected --target=build --parallel --max-parallel=3
      - run: npx nx affected --target=test --parallel --max-parallel=2 --code-coverage
      - run: npx nx affected --target=e2e --parallel --max-parallel=2

      - name: Codecov upload
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  pr:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - uses: actions/checkout@v3
      - run: |
            git fetch --no-tags --prune origin master
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
        with:
          main-branch-name: 'master'
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: '16'
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: npx nx affected --base=origin/master --target=lint --parallel --max-parallel=3
      - run: npx nx affected --base=origin/master --target=build --parallel --max-parallel=3
      - run: npx nx affected --base=origin/master --target=test --parallel --max-parallel=2 --code-coverage
      - run: npx nx affected --base=origin/master --target=e2e --parallel --max-parallel=2

      - name: Clean before merge
        run: pnpm cleanBeforeMerge

      - name: Codecov upload
        uses: codecov/codecov-action@v2
        with:
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }}
