name: 'Forms Release'

on:
  workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: yarn install --frozen-lockfile --non-interactive --no-progress --prefer-offline
      - run: yarn commitlint --from=master
      - run: yarn nx affected:lint --base=master
      - run: yarn nx affected:build --base=master
      # @NOTICE find a way to use affected:test with flag (if that possible??)
      - run: yarn nx affected:test --base=master
      - run: yarn nx affected:e2e --headless --base=master
      - name: Codecov upload
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  release:
    runs-on: ubuntu-latest

    needs: [test]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: yarn install --frozen-lockfile --non-interactive --no-progress --prefer-offline
      - name: Setup git user to "🤖 Release Bot"
        run: git config user.email "-" && git config user.name "🤖 Release Bot"
      - name: Version
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # Use npx instead of yarn because yarn automagically sets NPM_* environment variables
        # like NPM_CONFIG_REGISTRY so npm publish ends up ignoring the .npmrc file
        # which is set up by `setup-node` action.
        run: npx nx affected --base=master --releaseAs=minor --target=version
      - name: Tag last release
        run: git tag -f last-release
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          force: true
          tags: true
