name: 'Forms Release'

on:
  workflow_dispatch:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Checkout [master]
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
        with:
          main-branch-name: 'master'
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: yarn install --frozen-lockfile --non-interactive --no-progress --prefer-offline
      - run: yarn commitlint --from=master
      - run: yarn nx affected:lint --base=master
      - run: yarn nx affected:build --base=master
      - run: yarn nx affected:test --base=master
      # - name: Codecov upload
      #   uses: codecov/codecov-action@v2
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}

  release:
    runs-on: ubuntu-latest

    needs: [test]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          registry-url: https://registry.npmjs.org
      - run: yarn install --frozen-lockfile --non-interactive --no-progress --prefer-offline
      - name: Setup git user to "🤖 Release Bot"
        run: git config user.email "-" && git config user.name "🤖 Release Bot"
      - name: Version
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # Use npx instead of yarn because yarn auto-magically sets NPM_* environment variables
        # like NPM_CONFIG_REGISTRY so npm publish ends up ignoring the .npmrc file
        # which is set up by `setup-node` action.
        # run: npx nx affected --base=master --releaseAs=minor --target=version
        run: |
          npx --no-install nx version form-builder --baseBranch=master --releaseAs=minor --dryRun \
          && npx --no-install nx version form-validation-rule-list --baseBranch=master --releaseAs=minor --dryRun \
          && npx --no-install nx version form-redux --baseBranch=master --releaseAs=minor --dryRun
      - name: Tag last release
        run: git tag -f last-release
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          force: true
          tags: true
